import { CodeGenForTs } from '../../codegen';
import { Root } from '../../models';

const root = new Root({});

const HD = `
  /* 该文件由 Nad CLI 生成，请勿手改 */
  /* This file is generated by Nad CLI, do not edit manually. */
  /* eslint-disable */
`;

test('basic', () => {
  const code = new CodeGenForTs(root, { base: '' }).toString();
  expect(code).toMatchCode(HD);
  expect(code).toMatchCode(`
    import { NadInvoker } from '@huolala-tech/nad-runtime';
    import type { Settings } from '@huolala-tech/nad-runtime';

    export class Runtime<T = unknown> extends NadInvoker<T> {
      public static base = '';
    }
  `);
});

test('noHead', () => {
  const code = new CodeGenForTs(root, { base: '', noHead: true }).toString();
  expect(code).not.toMatchCode(HD);
});

test('custom base', () => {
  const code = new CodeGenForTs(root, { base: 'http//localhost' }).toString();
  expect(code).toMatchCode(`
    export class Runtime<T = unknown> extends NadInvoker<T> {
      public static base = 'http//localhost';
    }
  `);
});

test('custom runtimePkgName', () => {
  const code = new CodeGenForTs(root, { base: '', runtimePkgName: '@xxx/nad-runtime' }).toString();
  expect(code).toMatchCode(`
    import { NadInvoker } from '@xxx/nad-runtime';
    import type { Settings } from '@xxx/nad-runtime';
  `);
});
