/* 该文件由 Nad CLI 生成，请勿手改 */
/* This file is generated by Nad CLI, do not edit manually. */
/* eslint-disable */

/**
 * NadResult
 * @iface cn.lalaframework.nad.models.NadResult
 */
export interface NadResult {
  classes: NadClass[];
  enums: NadEnum[];
  modules: NadModule[];
  routes: NadRoute[];
}

/**
 * NadClass
 * @iface cn.lalaframework.nad.models.NadClass
 */
export interface NadClass extends NadDef {
  interfaces: string[];
  members: NadMember[];
  superclass?: string;
  typeParameters: string[];
}

/**
 * NadDef
 * @iface cn.lalaframework.nad.models.NadDef
 */
export interface NadDef {
  annotations: NadAnnotation[];
  name: string;
}

/**
 * NadAnnotation
 * @iface cn.lalaframework.nad.models.NadAnnotation
 */
export interface NadAnnotation {
  attributes: Record<string, any>;
  type: string;
}

/**
 * NadMember
 * @iface cn.lalaframework.nad.models.NadMember
 */
export interface NadMember {
  annotations: NadAnnotation[][];
  name: string;
  type?: string;
}

/**
 * NadEnum
 * @iface cn.lalaframework.nad.models.NadEnum
 */
export interface NadEnum extends NadDef {
  constants: NadEnumConstant<any>[];
}

/**
 * NadEnumConstant
 * @iface cn.lalaframework.nad.models.NadEnumConstant
 */
export interface NadEnumConstant<T> {
  annotations: NadAnnotation[];
  name: string;
  properties: Record<string, any>;
  value: any;
}

/**
 * NadModule
 * @iface cn.lalaframework.nad.models.NadModule
 */
export type NadModule = NadDef;

/**
 * NadRoute
 * @iface cn.lalaframework.nad.models.NadRoute
 */
export interface NadRoute {
  annotations: NadAnnotation[];
  bean: string;
  consumes: string[];
  headers: NameValuePair[];
  methods: string[];
  name: string;
  parameters: NadParameter[];
  patterns: string[];
  produces: string[];
  returnType: string;
}

/**
 * NameValuePair
 * @iface cn.lalaframework.nad.models.NameValuePair
 */
export interface NameValuePair {
  name: string;
  value?: string;
}

/**
 * NadParameter
 * @iface cn.lalaframework.nad.models.NadParameter
 */
export interface NadParameter {
  annotations: NadAnnotation[];
  name?: string;
  type: string;
}
