name: Unit Test for Java

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - nad-java-core
          - nad-java-sdk
        prepare:
          - :
          - sed -i 's/2\.2\.6.RELEASE/2.7.13/' pom.xml && sed -i 's/5\.2\.5.RELEASE/5.3.28/' pom.xml
          - sed -i 's/2\.2\.6.RELEASE/3.1.1/' pom.xml && sed -i 's/5\.2\.5.RELEASE/6.0.10/' pom.xml

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
      - run: cd ${{ matrix.project }} && ${{ matrix.prepare }} && mvn -B test
      - uses: codecov/codecov-action@v3
        with:
          directory: ${{ matrix.project }}
          flags: ${{ matrix.project }}
