name: Unit Test for Java

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sb:
          - spring-boot-2.2
          - spring-boot-2.7
          - spring-boot-3.1

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      # For nad-java-core
      - run: cd nad-java-core && mvn install -f ${{ matrix.sb }}.pom.xml
      - uses: codecov/codecov-action@v3
        with:
          directory: nad-java-core
          flags: nad-java-core-${{ matrix.sb }}

      # For nad-java-sdk
      - run: cd nad-java-sdk && mvn test -f ${{ matrix.sb }}.pom.xml
      - uses: codecov/codecov-action@v3
        with:
          directory: nad-java-sdk
          flags: nad-java-sdk-${{ matrix.sb }}
