name: Unit Test for Java

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        prepare:
          # Spring Boot 2.2.6.RELEASE (by default)
          - ":"
          # Spring Boot 2.7.13
          - sed -i 's/2\.2\.6.RELEASE/2.7.13/' pom.xml && sed -i 's/5\.2\.5.RELEASE/5.3.28/' pom.xml
          # Spring Boot 3.1.1
          - sed -i 's/2\.2\.6.RELEASE/3.1.1/' pom.xml && sed -i 's/5\.2\.5.RELEASE/6.0.10/' pom.xml

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      # For nad-java-core
      - run: cd nad-java-core && ${{ matrix.prepare }} && mvn install
      - uses: codecov/codecov-action@v3
        with:
          directory: nad-java-core
          flags: nad-java-core

      # For nad-java-sdk
      - run: cd nad-java-sdk && ${{ matrix.prepare }} && mvn -B test
      - uses: codecov/codecov-action@v3
        with:
          directory: nad-java-sdk
          flags: nad-java-sdk
