name: Unit Test for Java

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - nad-java-core
          - nad-java-sdk
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
      - run: cd ${{ matrix.project }} && mvn -B test
      - uses: codecov/codecov-action@v3
        with:
          directory: ${{ matrix.project }}
          flags: ${{ matrix.project }}
