name: Unit Test (nad-java-sdk)

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nad-java-sdk
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
      - run: mvn test
      - uses: codecov/codecov-action@v3
        with:
          flags: nad-java-sdk
