name: Unit Test (nad-cli)

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - run: cd nad-cli
      - run: yarn
      - run: yarn test
      - uses: codecov/codecov-action@v3
        with:
          flags: nad-cli
